version: ">= 0.14.1"

formatter: markdown table

header-from: main.tf
footer-from: ""

sections:
  hide:
    - providers
    - resources
    - data-sources

recursive:
  enabled: false
  path: modules

content: ""

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    {{ .Content }}

    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 3
  lockfile: true
  required: true
  sensitive: true
  type: true
